# Generates Find*.cmake modules at configure time into ${PROJECT_BINARY_DIR}/cmake/.
# These are installed alongside the library so downstream consumers can use
# module-mode find_package().

# Generates a FindXxx.cmake module for a library.
#
# Required arguments:
#   MODULE_NAME  — find-module name without "Find" prefix (e.g. "BehaviorTree")
#   NAMESPACE    — CMake namespace for the imported target (e.g. "BehaviorTree")
#   TARGET_NAME  — imported target name without namespace (e.g. "behaviorTree")
#   HEADER_NAME  — header path to locate via find_path (optional, e.g. "behaviorTree/iNode.hpp")
#   PACKAGE_DOC  — human-readable package name for docs (e.g. "behavior-tree")
function(generate_find_module)
    cmake_parse_arguments(ARG "" "MODULE_NAME;NAMESPACE;TARGET_NAME;HEADER_NAME;PACKAGE_DOC" "" ${ARGN})

    if(NOT ARG_MODULE_NAME OR NOT ARG_NAMESPACE OR NOT ARG_TARGET_NAME OR NOT ARG_PACKAGE_DOC)
        message(FATAL_ERROR "generate_find_module requires MODULE_NAME, NAMESPACE, TARGET_NAME, HEADER_NAME (optional), and PACKAGE_DOC")
    endif()

    set(_out "${PROJECT_BINARY_DIR}/cmake/Find${ARG_MODULE_NAME}.cmake")

    # Write the FindModule.cmake file directly
    file(WRITE "${_out}" "# - Try to find the ${ARG_MODULE_NAME} library\n")
    file(APPEND "${_out}" "# Once done, this will define\n")
    file(APPEND "${_out}" "#  ${ARG_MODULE_NAME}_FOUND - System has ${ARG_MODULE_NAME}\n")
    file(APPEND "${_out}" "#  ${ARG_MODULE_NAME}_INCLUDE_DIRS - The ${ARG_MODULE_NAME} include directories\n")
    file(APPEND "${_out}" "#  ${ARG_MODULE_NAME}_LIBRARIES - The libraries needed to use ${ARG_MODULE_NAME}\n")
    file(APPEND "${_out}" "#  ${ARG_MODULE_NAME}_DEFINITIONS - Compiler switches required for using ${ARG_MODULE_NAME}\n\n")

    if(ARG_HEADER_NAME)
        file(APPEND "${_out}" "find_path(${ARG_MODULE_NAME}_INCLUDE_DIR\n")
        file(APPEND "${_out}" "  NAMES ${ARG_HEADER_NAME}\n")
        file(APPEND "${_out}" "  PATHS\n")
        file(APPEND "${_out}" "    \${CMAKE_PREFIX_PATH}\n")
        file(APPEND "${_out}" "    /usr/include\n")
        file(APPEND "${_out}" "    /usr/local/include\n")
        file(APPEND "${_out}" ")\n\n")
    endif()

    file(APPEND "${_out}" "find_library(${ARG_MODULE_NAME}_SHARED_LIBRARY\n")
    file(APPEND "${_out}" "  NAMES ${ARG_TARGET_NAME}\n")
    file(APPEND "${_out}" "  PATHS\n")
    file(APPEND "${_out}" "    \${CMAKE_PREFIX_PATH}\n")
    file(APPEND "${_out}" "    /usr/lib\n")
    file(APPEND "${_out}" "    /usr/local/lib\n")
    file(APPEND "${_out}" ")\n\n")

    file(APPEND "${_out}" "find_library(${ARG_MODULE_NAME}_STATIC_LIBRARY\n")
    file(APPEND "${_out}" "  NAMES ${ARG_TARGET_NAME}_static\n")
    file(APPEND "${_out}" "  PATHS\n")
    file(APPEND "${_out}" "    \${CMAKE_PREFIX_PATH}\n")
    file(APPEND "${_out}" "    /usr/lib\n")
    file(APPEND "${_out}" "    /usr/local/lib\n")
    file(APPEND "${_out}" ")\n\n")

    file(APPEND "${_out}" "include(FindPackageHandleStandardArgs)\n")
    file(APPEND "${_out}" "find_package_handle_standard_args(${ARG_MODULE_NAME}\n")
    file(APPEND "${_out}" "  REQUIRED_VARS ${ARG_MODULE_NAME}_INCLUDE_DIR\n")
    file(APPEND "${_out}" "  VERSION_VAR ${ARG_MODULE_NAME}_VERSION\n")
    file(APPEND "${_out}" ")\n\n")

    file(APPEND "${_out}" "if(${ARG_MODULE_NAME}_FOUND)\n")
    file(APPEND "${_out}" "  if(${ARG_MODULE_NAME}_SHARED_LIBRARY)\n")
    file(APPEND "${_out}" "    add_library(${ARG_NAMESPACE}::${ARG_TARGET_NAME}_SHARED SHARED IMPORTED)\n")
    file(APPEND "${_out}" "    set_target_properties(${ARG_NAMESPACE}::${ARG_TARGET_NAME}_SHARED PROPERTIES\n")
    file(APPEND "${_out}" "      IMPORTED_LOCATION \${${ARG_MODULE_NAME}_SHARED_LIBRARY}\n")
    file(APPEND "${_out}" "      INTERFACE_INCLUDE_DIRECTORIES \${${ARG_MODULE_NAME}_INCLUDE_DIR}\n")
    file(APPEND "${_out}" "    )\n")
    file(APPEND "${_out}" "  endif()\n\n")

    file(APPEND "${_out}" "  if(${ARG_MODULE_NAME}_STATIC_LIBRARY)\n")
    file(APPEND "${_out}" "    add_library(${ARG_NAMESPACE}::${ARG_TARGET_NAME}_STATIC STATIC IMPORTED)\n")
    file(APPEND "${_out}" "    set_target_properties(${ARG_NAMESPACE}::${ARG_TARGET_NAME}_STATIC PROPERTIES\n")
    file(APPEND "${_out}" "      IMPORTED_LOCATION \${${ARG_MODULE_NAME}_STATIC_LIBRARY}\n")
    file(APPEND "${_out}" "      INTERFACE_INCLUDE_DIRECTORIES \${${ARG_MODULE_NAME}_INCLUDE_DIR}\n")
    file(APPEND "${_out}" "    )\n")
    file(APPEND "${_out}" "  endif()\n\n")

    file(APPEND "${_out}" "  add_library(${ARG_NAMESPACE}::${ARG_TARGET_NAME} INTERFACE)\n")
    file(APPEND "${_out}" "  if(${ARG_MODULE_NAME}_SHARED_LIBRARY AND ${ARG_MODULE_NAME}_STATIC_LIBRARY)\n")
    file(APPEND "${_out}" "    if(NOT DEFINED ${ARG_MODULE_NAME}_LIBRARY_TYPE)\n")
    file(APPEND "${_out}" "      set(${ARG_MODULE_NAME}_LIBRARY_TYPE "STATIC" CACHE STRING \"Library type for ${ARG_MODULE_NAME} (SHARED or STATIC)\")\n")
    file(APPEND "${_out}" "      set_property(CACHE ${ARG_MODULE_NAME}_LIBRARY_TYPE PROPERTY STRINGS SHARED STATIC)\n")
    file(APPEND "${_out}" "    endif()\n")
    file(APPEND "${_out}" "    if(${ARG_MODULE_NAME}_LIBRARY_TYPE STREQUAL "STATIC")\n")
    file(APPEND "${_out}" "      target_link_libraries(${ARG_NAMESPACE}::${ARG_TARGET_NAME} INTERFACE ${ARG_NAMESPACE}::${ARG_TARGET_NAME}_STATIC)\n")
    file(APPEND "${_out}" "    else()\n")
    file(APPEND "${_out}" "      target_link_libraries(${ARG_NAMESPACE}::${ARG_TARGET_NAME} INTERFACE ${ARG_NAMESPACE}::${ARG_TARGET_NAME}_SHARED)\n")
    file(APPEND "${_out}" "    endif()\n")
    file(APPEND "${_out}" "  elseif(${ARG_MODULE_NAME}_SHARED_LIBRARY)\n")
    file(APPEND "${_out}" "    target_link_libraries(${ARG_NAMESPACE}::${ARG_TARGET_NAME} INTERFACE ${ARG_NAMESPACE}::${ARG_TARGET_NAME}_SHARED)\n")
    file(APPEND "${_out}" "  elseif(${ARG_MODULE_NAME}_STATIC_LIBRARY)\n")
    file(APPEND "${_out}" "    target_link_libraries(${ARG_NAMESPACE}::${ARG_TARGET_NAME} INTERFACE ${ARG_NAMESPACE}::${ARG_TARGET_NAME}_STATIC)\n")
    file(APPEND "${_out}" "  endif()\n")
    file(APPEND "${_out}" "endif()\n")
endfunction()