include(GNUInstallDirs)
include(CMakePackageConfigHelpers)

# Installs a library with proper CMake export sets and config-mode package files.
#
# Required arguments:
#   PACKAGE_NAME  — kebab-case package name (e.g. "behavior-tree")
#   NAMESPACE     — CMake namespace for exports (e.g. "behavior-tree")
#
# Optional arguments (at least one required):
#   STATIC_TARGET    — static library target name (e.g. behaviorTree)
#   SHARED_TARGET    — shared library target name (e.g. behaviorTreeShared)
#   INTERFACE_TARGET — interface library target name (e.g. behaviorTreeInterface)
#
# Expects the following file to exist (generated by config-template.cmake):
#   ${PROJECT_BINARY_DIR}/cmake/${PACKAGE_NAME}-config.cmake.in
function(library_install_rules)
    cmake_parse_arguments(ARG "" "PACKAGE_NAME;NAMESPACE;STATIC_TARGET;SHARED_TARGET;INTERFACE_TARGET" "" ${ARGN})

    if(NOT ARG_PACKAGE_NAME)
        message(FATAL_ERROR "library_install_rules requires PACKAGE_NAME")
    endif()
    if(NOT ARG_NAMESPACE)
        message(FATAL_ERROR "library_install_rules requires NAMESPACE")
    endif()
    if(NOT ARG_STATIC_TARGET AND NOT ARG_SHARED_TARGET AND NOT ARG_INTERFACE_TARGET)
        message(FATAL_ERROR "library_install_rules requires at least one of STATIC_TARGET, SHARED_TARGET, or INTERFACE_TARGET")
    endif()

    set(_pkg "${ARG_PACKAGE_NAME}")
    set(_ns "${ARG_NAMESPACE}")

    # Override the default CMAKE_INSTALL_DOCDIR to match the package name convention.
    set(CMAKE_INSTALL_DOCDIR "share/doc/${_pkg}")

    # Install static library target
    if(ARG_STATIC_TARGET)
        install(
            TARGETS ${ARG_STATIC_TARGET}
            EXPORT ${_pkg}-static-targets
            ARCHIVE
                DESTINATION ${CMAKE_INSTALL_LIBDIR}
                COMPONENT Static
            INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
        )
    endif()

    # Install shared library target
    if(ARG_SHARED_TARGET)
        install(
            TARGETS ${ARG_SHARED_TARGET}
            EXPORT ${_pkg}-shared-targets
            LIBRARY
                DESTINATION ${CMAKE_INSTALL_LIBDIR}
                COMPONENT Shared
            RUNTIME
                DESTINATION ${CMAKE_INSTALL_BINDIR}
                COMPONENT Shared
            INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
        )
    endif()

    # Install interface library target
    if(ARG_INTERFACE_TARGET)
        install(
            TARGETS ${ARG_INTERFACE_TARGET}
            EXPORT ${_pkg}-interface-targets
            INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
            COMPONENT Interface
        )
    endif()

    if(NOT EXISTS "${PROJECT_SOURCE_DIR}/include")
        message(WARNING "library_install_rules: no include/ directory found at "
            "'${PROJECT_SOURCE_DIR}/include' — no public headers will be installed")
    endif()

    # Install public headers for each active component
    foreach(_comp Static Shared Interface)
        string(TOUPPER "${_comp}" _comp_upper)
        if(ARG_${_comp_upper}_TARGET)
            install(
                DIRECTORY ${PROJECT_SOURCE_DIR}/include/
                DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
                COMPONENT ${_comp}
                PATTERN "*.in" EXCLUDE
            )
        endif()
    endforeach()

    # Install the export sets
    if(ARG_STATIC_TARGET)
        install(
            EXPORT ${_pkg}-static-targets
            FILE ${_pkg}-static-targets.cmake
            NAMESPACE ${_ns}::
            DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_pkg}
            COMPONENT Static
        )
    endif()

    if(ARG_SHARED_TARGET)
        install(
            EXPORT ${_pkg}-shared-targets
            FILE ${_pkg}-shared-targets.cmake
            NAMESPACE ${_ns}::
            DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_pkg}
            COMPONENT Shared
        )
    endif()

    if(ARG_INTERFACE_TARGET)
        install(
            EXPORT ${_pkg}-interface-targets
            FILE ${_pkg}-interface-targets.cmake
            NAMESPACE ${_ns}::
            DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_pkg}
            COMPONENT Interface
        )
    endif()

    # Generate the package config and version files
    configure_package_config_file(
        ${PROJECT_BINARY_DIR}/cmake/${_pkg}-config.cmake.in
        ${PROJECT_BINARY_DIR}/${_pkg}-config.cmake
        INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_pkg}
    )

    write_basic_package_version_file(
        ${PROJECT_BINARY_DIR}/${_pkg}-config-version.cmake
        VERSION ${PROJECT_VERSION}
        COMPATIBILITY SameMajorVersion
    )

    # Install cmake config files for each active component
    foreach(_comp Static Shared Interface)
        string(TOUPPER "${_comp}" _comp_upper)
        if(ARG_${_comp_upper}_TARGET)
            install(
                FILES
                    ${PROJECT_BINARY_DIR}/${_pkg}-config.cmake
                    ${PROJECT_BINARY_DIR}/${_pkg}-config-version.cmake
                DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_pkg}
                COMPONENT ${_comp}
            )
        endif()
    endforeach()

    # Install generated documentation
    if(BUILD_DOCS AND DOXYGEN_FOUND)
        install(
            DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/docs/html/"
            DESTINATION "${CMAKE_INSTALL_DOCDIR}"
            COMPONENT Docs
            OPTIONAL
        )
    endif()
endfunction()
