include(GNUInstallDirs)
include(CMakePackageConfigHelpers)

# Installs a library that provides static, shared, and interface (header-only)
# variants with proper CMake export sets, config-mode package files, and
# module-mode find modules.
#
# Required arguments:
#   PACKAGE_NAME       — kebab-case package name (e.g. "behavior-tree")
#   NAMESPACE          — CMake namespace for exports (e.g. "behavior-tree")
#   STATIC_TARGET      — static library target name (e.g. behaviorTree)
#   SHARED_TARGET      — shared library target name (e.g. behaviorTreeShared)
#   INTERFACE_TARGET   — interface library target name (e.g. behaviorTreeInterface)
#
# Expects the following files to exist (generated by find-modules.cmake and
# config-template.cmake):
#   ${PROJECT_BINARY_DIR}/cmake/Find<ModuleName>Static.cmake
#   ${PROJECT_BINARY_DIR}/cmake/Find<ModuleName>Shared.cmake
#   ${PROJECT_BINARY_DIR}/cmake/Find<ModuleName>Interface.cmake
#   ${PROJECT_BINARY_DIR}/cmake/${PACKAGE_NAME}-config.cmake.in
function(library_install_rules)
    cmake_parse_arguments(ARG "" "PACKAGE_NAME;NAMESPACE;STATIC_TARGET;SHARED_TARGET;INTERFACE_TARGET" "" ${ARGN})

    if(NOT ARG_PACKAGE_NAME OR NOT ARG_NAMESPACE OR NOT ARG_STATIC_TARGET OR NOT ARG_SHARED_TARGET OR NOT ARG_INTERFACE_TARGET)
        message(FATAL_ERROR "library_install_rules requires PACKAGE_NAME, NAMESPACE, STATIC_TARGET, SHARED_TARGET, and INTERFACE_TARGET")
    endif()

    set(_pkg "${ARG_PACKAGE_NAME}")
    set(_ns "${ARG_NAMESPACE}")

    # Override the default CMAKE_INSTALL_DOCDIR to match the package name convention.
    set(CMAKE_INSTALL_DOCDIR "share/doc/${_pkg}")

    # Install static library target
    install(
        TARGETS ${ARG_STATIC_TARGET}
        EXPORT ${_pkg}-static-targets
        ARCHIVE
            DESTINATION ${CMAKE_INSTALL_LIBDIR}
            COMPONENT Static
        INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
    )

    # Install shared library target
    install(
        TARGETS ${ARG_SHARED_TARGET}
        EXPORT ${_pkg}-shared-targets
        LIBRARY
            DESTINATION ${CMAKE_INSTALL_LIBDIR}
            COMPONENT Shared
        RUNTIME
            DESTINATION ${CMAKE_INSTALL_BINDIR}
            COMPONENT Shared
        INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
    )

    # Install interface library target
    install(
        TARGETS ${ARG_INTERFACE_TARGET}
        EXPORT ${_pkg}-interface-targets
        INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
        COMPONENT Interface
    )

    # Install public headers for each component
    foreach(_comp Static Shared Interface)
        install(
            DIRECTORY ${PROJECT_SOURCE_DIR}/include/
            DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
            COMPONENT ${_comp}
        )
    endforeach()

    # Install the export sets
    install(
        EXPORT ${_pkg}-static-targets
        FILE ${_pkg}-static-targets.cmake
        NAMESPACE ${_ns}::
        DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_pkg}
        COMPONENT Static
    )

    install(
        EXPORT ${_pkg}-shared-targets
        FILE ${_pkg}-shared-targets.cmake
        NAMESPACE ${_ns}::
        DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_pkg}
        COMPONENT Shared
    )

    install(
        EXPORT ${_pkg}-interface-targets
        FILE ${_pkg}-interface-targets.cmake
        NAMESPACE ${_ns}::
        DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_pkg}
        COMPONENT Interface
    )

    # Generate the package config and version files
    configure_package_config_file(
        ${PROJECT_BINARY_DIR}/cmake/${_pkg}-config.cmake.in
        ${PROJECT_BINARY_DIR}/${_pkg}-config.cmake
        INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_pkg}
    )

    write_basic_package_version_file(
        ${PROJECT_BINARY_DIR}/${_pkg}-config-version.cmake
        VERSION ${PROJECT_VERSION}
        COMPATIBILITY SameMajorVersion
    )

    # Install cmake config files for each component
    foreach(_comp Static Shared Interface)
        install(
            FILES
                ${PROJECT_BINARY_DIR}/${_pkg}-config.cmake
                ${PROJECT_BINARY_DIR}/${_pkg}-config-version.cmake
            DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_pkg}
            COMPONENT ${_comp}
        )
    endforeach()

    # Install the component-specific find modules for module-mode find_package
    # These are expected to have been generated by find-modules.cmake into
    # ${PROJECT_BINARY_DIR}/cmake/
    file(GLOB _find_modules "${PROJECT_BINARY_DIR}/cmake/Find*.cmake")
    foreach(_fm ${_find_modules})
        get_filename_component(_fm_name "${_fm}" NAME)
        if(_fm_name MATCHES "Static\\.cmake$")
            set(_fm_comp Static)
        elseif(_fm_name MATCHES "Shared\\.cmake$")
            set(_fm_comp Shared)
        elseif(_fm_name MATCHES "Interface\\.cmake$")
            set(_fm_comp Interface)
        else()
            continue()
        endif()
        install(
            FILES "${_fm}"
            DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_pkg}
            COMPONENT ${_fm_comp}
        )
    endforeach()

    # Install generated documentation
    if(BUILD_DOCS AND DOXYGEN_FOUND)
        install(
            DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/docs/html/"
            DESTINATION "${CMAKE_INSTALL_DOCDIR}"
            COMPONENT Docs
            OPTIONAL
        )
    endif()
endfunction()
